### ISSUE TITLE
CID怎么获取

### ISSUE THREAD

**Issue by JerryShiruiYan** [FrostZhang/localtuya_getway#2]
麻烦问一下，设备的CID是怎么获取的？我在Tuya IoT页面上没有找到。是需要监听么？

**Comment by FrostZhang** [comment]
见 https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md

在linux系统控制台
npm i @tuyapi/cli -g
tuya-cli wizard

**Comment by JerryShiruiYan** [comment]
多谢！
